version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-mtips
    ports:
      - "80:80"
    volumes:
      - ./projects/main:/var/www/main
      - ./projects/admin:/var/www/admin
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-config/nginx/run_nginx.sh:/etc/nginx/run_nginx.sh
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d/
    command: /etc/nginx/run_nginx.sh
    depends_on:
      - main
      - admin
      - analytics
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
  main:
    build:
      context: docker-config/php-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.3'
        DOCKER_PHP_ENABLE_XDEBUG: 'off'
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www/main
    container_name: main
    volumes:
      - ./projects/main:/var/www/main
      - ./docker-config/php-workspace/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
      - "6001:6001"
    networks:
      - backend
    extra_hosts:
      - 'main.m-tips.local:192.168.65.1'
  admin:
    build:
      context: docker-config/php-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.3'
        DOCKER_PHP_ENABLE_XDEBUG: 'off'
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www/admin
    container_name: admin
    volumes:
      - ./projects/admin:/var/www/admin
      - ./docker-config/php-workspace/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:8000"
      - "6002:6002"
    networks:
      - backend
    extra_hosts:
      - 'admin.m-tips.local:192.168.65.1'
  mariadb:
    image: mariadb:11.2.2
    container_name: mariadb-mtips
    restart: unless-stopped
    volumes:
      - ./docker-config/mariadb/data:/var/lib/mysql
      - ./docker-config/mariadb/conf.d:/etc/mysql/conf.d
      - ./docker-config/mariadb/logs:/var/log/mysql/
      - ./docker-config/mariadb/dump:/dump
    ports:
      - "${MARIADB_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
  postgres:
    build:
      context: docker-config/postgresql
      dockerfile: Dockerfile
    container_name: postgres-timescaledb
    environment:
      POSTGRES_DB: mtips
      POSTGRES_USER: mtips
      POSTGRES_PASSWORD: mtips
    volumes:
      - ./docker-config/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  phpmyadmin:
    platform: linux/x86_64
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mtips
    #    restart: always
    ports:
      - "${PMA_PORT}:80"
    networks:
      - backend
    environment:
      PMA_HOST: mariadb
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ianfoxdeveloper@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend
  analytics:
    build:
      context: docker-config/analytics
      dockerfile: Dockerfile
    container_name: analytics-mtips
    command: uvicorn main:app --host 0.0.0.0 --port 9050 --reload
    volumes:
      - ./projects/analytics:/app
    ports:
      - "9050:9050"
    networks:
      - backend
    extra_hosts:
      - 'analytics.m-tips.local:192.168.65.1'